## ADDITION METHOD

In [1]:
import tensorflow as tf
import numpy as np

## add scaler

In [2]:
a=10
b=100
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=110>

## add 2 list

In [3]:
a=[1,2,3,4]
b=[5,6,7,8]
tf.add(a,b)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12])>

## add 2 tuple

In [4]:
a=(1,2,3,4,5)
b=(10,11,12,13,14)
tf.add(a,b)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([11, 13, 15, 17, 19])>

## add list tupple with scaler

In [5]:
a=[1,12,13,14,16]
b=100
tf.add(a,b)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([101, 112, 113, 114, 116])>

In [6]:
a=100
b=(100,200,300,400,500)
tf.add(a,b)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([200, 300, 400, 500, 600])>

## add list/tupple in different size

In [7]:
li1=[1,2,3,4]
li2=[1,2]
tf.add(li1,li2)

InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [4] vs. [2] [Op:AddV2]

## add numpy array

In [8]:
npa1=np.array([1,2,3])
npa2=np.array([1,2,3])
tf.add(npa1,npa2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6])>

## add numpy array with scaler

In [9]:
npa3=np.array([1,2,3])
npa4=10
tf.add(npa3,npa4)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 12, 13])>

In [11]:
npa1=np.array([1,2,3])
npa2=np.array([[1]])
tf.add(npa1,npa2)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[2, 3, 4]])>

## add two constant tensor

In [12]:
con1=tf.constant([1,2,3,4],tf.float32)
con2=tf.constant([1,2,3,4],tf.float32)
tf.add(con1,con2)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2., 4., 6., 8.], dtype=float32)>

## add constant and scaler

In [13]:
con1=tf.constant([1,2,3,4],tf.float32)
con2=10
tf.add(con1,con2)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([11., 12., 13., 14.], dtype=float32)>

## add variable tf

In [16]:
var1=tf.Variable([1,2,3,4])
var2=tf.Variable([2,3,5,5])
tf.add(var1,var2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 5, 8, 9])>

## variable with scaler

In [17]:
var1=tf.Variable([1,2,3,4])
var2=100
tf.add(var1,var2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([101, 102, 103, 104])>

## add two number different size

In [20]:
z=np.ones(6).reshape(1,2,1,3)
z

array([[[[1., 1., 1.]],

        [[1., 1., 1.]]]])

In [22]:
y=np.ones(6).reshape(2,1,3,1)
y

array([[[[1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.]]]])

In [25]:
tf.add(z,y)

<tf.Tensor: shape=(2, 2, 3, 3), dtype=float64, numpy=
array([[[[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]],


       [[[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]]])>

In [24]:
tf.add(z,y).shape.as_list

<bound method TensorShape.as_list of TensorShape([2, 2, 3, 3])>