In [1]:
import tensorflow as tf
import numpy as np

## multiply scaler

In [3]:
a=100
b=10

tf.multiply(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=1000>

## multiply two list

In [4]:
a=[1,2,3,4]
b=[5,6,7,8]
tf.multiply(a,b)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5, 12, 21, 32])>

## two tuple

In [5]:
a=(1,2,3,4,5)
b=(10,11,12,13,14)
tf.multiply(a,b)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([10, 22, 36, 52, 70])>

## multiply tuple or scaler

In [6]:
a=[1,12,13,14,16]
b=100
tf.multiply(a,b)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 100, 1200, 1300, 1400, 1600])>

## different size

In [7]:
li1=[1,2,3,4]
li2=[1,2]
tf.multiply(li1,li2)

InvalidArgumentError: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [4] vs. [2] [Op:Mul]

## multiply two array

In [8]:
npa1=np.array([1,2,3])
npa2=np.array([1,2,3])
tf.multiply(npa1,npa2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9])>

## multipkly constrator

In [9]:
con1=tf.constant([1,2,3,4],tf.float32)
con2=tf.constant([1,2,3,4],tf.float32)
tf.multiply(con1,con2)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4.,  9., 16.], dtype=float32)>

In [10]:
# variable
var1=tf.Variable([1,2,3,4])
var2=tf.Variable([2,3,5,5])
tf.multiply(var1,var2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 2,  6, 15, 20])>