## HOW TO CREATE ONES TENSOR

In [1]:
import tensorflow as tf

In [3]:
one=tf.ones((2,2),tf.float32)
one

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [7]:
one.numpy()[1][0]

1.0

## 3d

In [8]:
threeD=tf.ones((2,2,4),tf.float32)
threeD

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [10]:
threeD.shape

TensorShape([2, 2, 4])

## ones_like 

In [11]:
con=tf.constant([[1,2,3],[4,5,6]])
con

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [12]:
one2d_con=tf.ones_like(con,tf.int32)
one2d_con

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

In [19]:
var=tf.Variable([[1,2,3],[4,5,6]])
var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [21]:
one2d_var=tf.ones_like(var,tf.int32)
one2d_var

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

## initilizer

In [22]:
def one_variable(shape,dtype,initializer):
    return tf.Variable(initializer(shape=shape,dtype=dtype))
    

In [24]:
one_variable((2,2),tf.int32,tf.ones_initializer())

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 1],
       [1, 1]])>

In [25]:
one_variable((2,2,5),tf.int32,tf.ones_initializer())

<tf.Variable 'Variable:0' shape=(2, 2, 5) dtype=int32, numpy=
array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])>