In [1]:
import tensorflow as tf

In [3]:
st1=tf.SparseTensor(indices=[[2,3],[4,5]],values=[10,20],dense_shape=[3,10])
st1

SparseTensor(indices=tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))

## create parse tensor from dense

In [4]:
import numpy as np

In [6]:
array_A=np.array([[1,0,0,0],
                  [0,0,0,0],
                  [0,0,2,0],
                  [0,0,0,4],])
array_A

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])

In [9]:
a=tf.sparse.from_dense(array_A)
a

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 4], shape=(3,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))

## exact a value of indices,values, shape

In [13]:
a.values.numpy().tolist()

[1, 2, 4]

In [16]:
a.indices.numpy().tolist()

[[0, 0], [2, 2], [3, 3]]

In [19]:
a.dense_shape.numpy().tolist()

[4, 4]

## sparse tensor to dense

In [20]:
dt_sparse=tf.sparse.to_dense(a)
dt_sparse

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])>

In [23]:
dt_sparse.numpy()

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])

## mathametical operation on sparse tensor

In [25]:
p_add=tf.sparse.add(a,a)
p_add

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([2 4 8], shape=(3,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))

In [29]:
tf.sparse.to_dense(p_add).numpy()

array([[2, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 8]])