## import

In [1]:
import tensorflow as tf
import numpy as np

## version check

In [2]:
print(tf.__version__)   
print(np.__version__)

2.12.0
1.23.5


## check gpu availiblity

In [3]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

## create integer constant

In [4]:
a=tf.constant(10)
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

## create float constant

In [5]:
a=tf.constant(10.3)
a

<tf.Tensor: shape=(), dtype=float32, numpy=10.3>

## STRING

In [6]:
a=tf.constant("i am soiurik parui ")
a

<tf.Tensor: shape=(), dtype=string, numpy=b'i am soiurik parui '>

## boolean

In [8]:
a=tf.constant(True)
a

<tf.Tensor: shape=(), dtype=bool, numpy=True>

## create numpy array/list/tupple

In [17]:
np_array=tf.constant([10,11,12,12,14,15])
np_array

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([10, 11, 12, 12, 14, 15])>

In [20]:
# 1d array
oned_array=tf.constant([1,2,3,4,5])
oned_array

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [24]:
#2d array
twod=tf.constant([[1,2,3],[4,5,6]])
twod

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]])>

In [25]:
twod1=tf.constant([[1,2,3],[4,5,6]],shape=(3,2),dtype="float64",name="twod")
twod1

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]])>

In [27]:
#n dimension array
nd=tf.constant([1,2,3,4,5,6,7,8,9,10,12,13],shape=(4,3),dtype=tf.int32)
nd

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 12, 13]])>

## type check

In [28]:
type(nd)

tensorflow.python.framework.ops.EagerTensor

## shape check

In [33]:
nd.shape
twod1.shape

TensorShape([3, 2])

## access constant value

In [34]:
nd.numpy()

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 12, 13]])

In [37]:
# if i need 3 arry
nd.numpy()[2]

array([7, 8, 9])

In [38]:
nd.numpy()[2][0]

7

In [40]:
# constant dtype check
nd.dtype

tf.int32

## mixed value not create tensor

In [42]:
a=tf.constant([1,1.2,"sourik"])
a  # error

ValueError: Can't convert Python sequence with mixed types to Tensor.

In [45]:
tf.constant(0, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>