In [5]:
import tensorflow as tf
import numpy as np

In [6]:
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [12]:
a=np.array([1,2,3,4,5,6])
b=tf.Variable(a)
b

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [13]:
b.name

'Variable:0'

In [14]:
b.shape

TensorShape([6])

In [15]:
b.dtype

tf.int32

In [20]:
b.numpy()[3]

4

In [21]:
type(b)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [ ]:
type(a)

## create tensorflow int,float,string,bool,complex number

In [53]:
t_f30=tf.Variable([1.2,2.2,3.2,4.5])
t_f30

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1.2, 2.2, 3.2, 4.5], dtype=float32)>

In [25]:
t_f=tf.Variable(['a','b','c'])
t_f

<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'a', b'b', b'c'], dtype=object)>

In [26]:
t_f=tf.Variable([True,False])
t_f

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>

In [32]:
t_cx=tf.Variable([4+7j,7+0j])
t_cx

<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([4.+7.j, 7.+0.j])>

## asign

In [42]:
t_f=tf.Variable(10.0)
t_f.assign(11)
t_f.assign_add(10)
t_f.assign_sub(19.0)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=2.0>

## create TF from constant tensorflow variable

In [43]:
t_con=tf.constant([1,2,3,4])
t_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [44]:
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

## create differnt shape in variable 

In [46]:
t_2d=tf.Variable([[54,76],[99,78]])
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[54, 76],
       [99, 78]])>

In [51]:
t2d_1=tf.Variable([[1,2,3],[4,5,6]],shape=(2,3),dtype='float64')
t2d_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float64, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]])>

## RESHAPE

In [62]:
a=tf.reshape(t_f30,shape=(2,2))

In [66]:
a.numpy()[1][0]

3.2

## get index of heighest value

In [67]:
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.2, 2.2],
       [3.2, 4.5]], dtype=float32)>

In [70]:
tf.argmax(a)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1], dtype=int64)>

In [71]:
tf.argmax(a).numpy()

array([1, 1], dtype=int64)

## convert/viewd as a tensor

In [73]:
t2d_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float64, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]])>

In [74]:
tf.convert_to_tensor(t2d_1)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]])>

## change or new value in tensor

In [82]:
t_f30

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1.2, 2.2, 3.2, 4.5], dtype=float32)>

In [83]:
t_f30.assign([10.1,20.2,30.4,60.6])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=float32, numpy=array([10.1, 20.2, 30.4, 60.6], dtype=float32)>

In [84]:
t_f30

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([10.1, 20.2, 30.4, 60.6], dtype=float32)>

## assign with another memory

In [85]:
t_f30.assign_add([1.2, 2.2, 3.2, 4.5])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=float32, numpy=array([11.3     , 22.400002, 33.6     , 65.1     ], dtype=float32)>

## can not change the shape and dtype also

In [91]:
t_f30.assign([1.2, 2.2, 3.2, 4.5,8.9])  # error for shape

ValueError: Cannot assign value to variable ' Variable:0': Shape mismatch.The variable shape (4,), and the assigned value shape (5,) are incompatible.

In [95]:
t_f30.assign([1, 2, 3, 4])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>