In [1]:
import tensorflow as tf

In [2]:
zero=tf.zeros((2,2),tf.float32)
zero

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

## 3d

In [3]:
zero3D=tf.zeros((2,2,4),tf.float32)
zero3D

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [4]:
zero3D.shape

TensorShape([2, 2, 4])

In [5]:
zero3D.numpy().tolist

<function ndarray.tolist>

In [6]:
con=tf.constant([[1,2,3],[4,5,6]])
con

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [7]:
zeros_con=tf.zeros_like(con,tf.int32)
zeros_con

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

In [8]:
var=tf.Variable([[1,2,3],[4,5,6],[7,8,9]])
var

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [10]:
var_zeros=tf.zeros_like(var)
var_zeros

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

In [11]:
var_2d=tf.Variable([[1,2,3],[4,5,6]])
var_2d

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [16]:
var_2d_like=tf.zeros_like(var_2d,dtype=tf.bool)
var_2d_like

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[False, False, False],
       [False, False, False]])>

## zeros initilizar

In [17]:
def zero_init(shape,dtype,initializer):
    return tf.Variable(initializer(shape=shape,dtype=dtype))

In [18]:
zero_init((2,2),tf.float32,tf.zeros_initializer())

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [20]:
zero_init((2,2,7),tf.bool,tf.zeros_initializer())

<tf.Variable 'Variable:0' shape=(2, 2, 7) dtype=bool, numpy=
array([[[False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False]],

       [[False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False]]])>

In [21]:
tf.Variable(tf.zeros_initializer()((2,2),tf.int32))

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[0, 0],
       [0, 0]])>